dist: xenial
# xenial is not supported before Nov 2018,  but trusty is still the default, python2
# https://blog.travis-ci.com/2018-11-08-xenial-release
# docker is another way to test out this FenicsSolver, there is no needed to specify a dist

sudo: required
language: python
python:
- '2.7'

services:
- docker

before_install:
- curl -s "https://get.fenicsproject.org" | bash

install:
# install the package to be tested
- echo "current working dir is $(pwd)"
- git clone https://github.com/qingfengxia/FenicsSolver.git
- cd FenicsSolver
- travis_retry sudo python setup.py install
- pwd
- if  [ -d 'examples' ] ; then cd examples; fi

# no need to run in interactive mode `-it`
script:
- echo "current working dir is $(pwd)"
- docker run -p 127.0.0.1:8000:8000 -v $(pwd):/home/fenics/shared -w /home/fenics/shared quay.io/fenicsproject/stable:current -c "pwd"
- docker exec  quay.io/fenicsproject/stable:current "python run_all_tests.py"